#!/bin/bash
LC_ALL=C
function dialogopart () {
	dispositivo=$(fdisk -l | grep "Disco" | awk '{print $2}' | sed 's/.$//g' | yad --center --no-click --list --title="Disco a particionar" --text="Seleccione el disco que desea particionar." --separator="" --column 'Dispositivo' --height 380 --width 150 --button="ACEPTAR":0)
	if [[ -z "$dispositivo" ]] ; then
		yad --center --window-icon=error --title="Error" --button="Ir atras":0 --button="Salir":1 --text="No selecciono nada. Debe escoger un disco."
		if [[ $? = 0 ]] ; then
			source refractainstaller-yad
		else
			exit 1
		fi
	fi
	for i in $(fdisk -l "$dispositivo" | grep "swap" | awk '{print $1}'); do
		swapoff $i
	done	
	for i in $(fdisk -l "$dispositivo" | grep "/dev" | grep -v "Disco" | awk '{print $1}'); do
		umount -f $i
	done
	lvremove -f $(pvdisplay $(echo $dispositivo"*") | grep "VG" | awk '{print $3}' | uniq)
	dd if=/dev/zero of="$dispositivo" bs=1024k count=1
	partprobe "$dispositivo"
	if [[ $(arch) = x86_64 ]]; then
		if [[ -f /sys/firmware/efi/runtime ]]; then
			parted -s "$dispositivo" -- mklabel gpt
			parted -a optimal -s "$dispositivo" -- mkpart primary fat32 3 260
			parted "$dispositivo" set 1 esp on
			mkfs.vfat -n BOOT -F 32 $(fdisk -l "$dispositivo" | grep "EFI" | awk '{print $1}')
			touch /tmp/efi
		else
			parted -s "$dispositivo" -- mklabel gpt
			parted -a optimal -s "$dispositivo" -- mkpart non-fs 2 3
			parted "$dispositivo" set 1 bios_grub on
			parted -a optimal -s "$dispositivo" -- mkpart primary ext4 3 260
			parted "$dispositivo" set 2 boot on
			mkfs.ext4 -L boot -F $(fdisk -l "$dispositivo" | grep "EFI" | awk '{print $1}')
		fi
	else
		parted -s "$dispositivo" -- mklabel msdos
		parted -a optimal -s "$dispositivo" -- mkpart primary ext4 3 260
		parted "$dispositivo" set 1 boot on
		mkfs.ext4 -L boot -F $(fdisk -l "$dispositivo" | grep "Linux" | awk '{print $1}')
	fi
	parted -a optimal -s "$dispositivo" -- mkpart primary linux-swap 260 1330
	mkswap -L swap -f $(fdisk -l "$dispositivo" | grep "swap" | awk '{print $1}')
}

function milvm () {
if yad --skip-taskbar --fixed --center --text-align=fill --borders=6 --title="ADVERTENCIA" --text="Se recomienda utilizar un sistema de energia de respaldo para utilizar LVM"; then	
	dialogopart
	if [[ $(parted -s "$dispositivo" -- print | grep "Partition" | awk '{print $3}') = msdos ]]; then
		parted -a optimal -s "$dispositivo" -- mkpart extended 1330 100%
		parted -a optimal -s "$dispositivo" -- mkpart logic ext2 1331 100%
		logica=$(parted -s "$dispositivo" -l | grep "1331" | awk '{print $1}')
		pvcreate -ffy $(echo $dispositivo"$logica")
		vgcreate -fy xanadu $(echo $dispositivo"$logica")
		lvcreate -l 100%FREE -n root xanadu
		partprobe "$dispositivo"
		mkfs.ext4 -F /dev/mapper/xanadu-root
		echo "$dispositivo" > /tmp/particionador
	else
		parted -a optimal -s "$dispositivo" -- mkpart non-fs 1331 100%
		parted "$dispositivo" set 4 lvm on
		casilvm=$(fdisk -l "$dispositivo" | grep "LVM" | awk '{print $1}')
		pvcreate -ffy "$casilvm"
		vgcreate -fy xanadu "$casilvm"
		lvcreate -l 100%FREE -n root xanadu
		partprobe "$dispositivo"
		mkfs.ext4 -F /dev/mapper/xanadu-root
		echo "$dispositivo" > /tmp/particionador
	fi
else
	source refractainstaller-yad
fi
}

function miparticion () {
	dialogopart
	parted -a optimal -s "$dispositivo" -- mkpart primary ext4 1331 100%
	partprobe "$dispositivo"
	mkfs.ext4 -L root -F $(fdisk -l "$dispositivo" | grep "Sistema de ficheros de Linux" | awk '{print $1}')
	echo "$dispositivo" > /tmp/particionador
}
