#!/bin/bash
LC_ALL=C
if [[ $USER != root ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
lock="/run/tor.lock"
lock2="/run/i2p.lock"
lock3="/run/mirouter.lock"
persistencia="/usr/bin/persistencia"
memoria=$(grep "MemTotal" /proc/meminfo | awk '{print $2}')
cpu=$(lscpu | grep "MHz" | awk '{print $3}')
miswap=$(fdisk -l | grep "swap" | awk '{print $1}')
quien=$(who | cut -d' ' -f1 | sort | uniq)
insta="apt -q update && apt -q -y --force-yes install"
miyad='yad --skip-taskbar --button=ACEPTAR:1 --fixed --center --text-align=fill --borders=6'
errores='yad --skip-taskbar --button=ACEPTAR:1 --fixed --center --text-align=fill --borders=6 --timeout=3 --title="ERROR"'
advertencia='yad --skip-taskbar --button=ACEPTAR:1 --fixed --center --text-align=fill --borders=6 --title="ADVERTENCIA"'
final='yad --skip-taskbar --button=ACEPTAR:1 --fixed --center --text-align=fill --borders=6 --timeout=3 --title="FINALIZADO"'
progreso='yad --fixed --progress --pulsate --auto-kill --skip-taskbar --center'
progresoz='zenity --progress --pulsate --no-cancel --auto-close'

function espera () {
	sleep 30 | "$progresoz" --text "Iniciando tor, por favor espere"
}

function progress_1 () {
	"$progresoz" --text "Instalando Software, esto proceso puede tomar varios minutos, por favor espere"
}

function progress_2 () {
	"$progreso" --progress-text="Instalando Software, esto proceso puede tomar varios minutos, por favor espere" --title="INSTALANDO"
}

function progress_limpiar_1 () {
	"$progresoz" --text "Realizando limpieza"
}

function progress_limpiar_2 () {
	"$progreso" --progress-text="Realizando limpieza" --title="LIMPIEZA"
}

function limpiar_1 () {
	history -c
	apt-get clean
	apt -y purge $(deborphan)
	rm -rf /var/cache/polipo/*
	rm -rf /root/.local/share/Trash/*
	rm -rf /home/*/.local/share/Trash/*
	rm -rf /home/*/.cache/*
}

function optimizacion_1 () {
	if ! [[ -f /root/.optimizado2 ]]; then
		dispositivo2=$(df / --output=source | tail -n1)
		dispositivo4=$(df -T | grep "$dispositivo2" | awk '{print $2}')
		if [[ "$dispositivo4" = xfs ]]; then
			echo "fs.xfs.age_buffer_centisecs = 1500" >> /etc/sysctl.conf
			echo "fs.xfs.error_level = 3" >> /etc/sysctl.conf
			echo "fs.xfs.filestream_centisecs = 3000" >> /etc/sysctl.conf
			echo "fs.xfs.inherit_noatime = 1" >> /etc/sysctl.conf
			echo "fs.xfs.inherit_nodefrag = 1" >> /etc/sysctl.conf
			echo "fs.xfs.inherit_nodump = 1" >> /etc/sysctl.conf
			echo "fs.xfs.inherit_nosymlinks = 0" >> /etc/sysctl.conf
			echo "fs.xfs.inherit_sync = 1" >> /etc/sysctl.conf
			echo "fs.xfs.irix_sgid_inherit = 0" >> /etc/sysctl.conf
			echo "fs.xfs.irix_symlink_mode = 0" >> /etc/sysctl.conf
			echo "fs.xfs.panic_mask = 0" >> /etc/sysctl.conf
			echo "fs.xfs.rotorstep = 1" >> /etc/sysctl.conf
			echo "fs.xfs.speculative_prealloc_lifetime = 300" >> /etc/sysctl.conf
			echo "fs.xfs.stats_clear = 0" >> /etc/sysctl.conf
			echo "fs.xfs.xfsbufd_centisecs = 100" >> /etc/sysctl.conf
			echo "fs.xfs.xfssyncd_centisecs = 3000" >> /etc/sysctl.conf
		fi
		chage -M 183 "$quien"
		adduser "$quien" sambashare
		if (( $memoria > 4096000 )); then
			for i in $quien; do
				echo "tmpfs /home/$i/.cache tmpfs noatime,noexec,nosuid,async,nodev,rw 0 0" >> /etc/fstab
			done
			aideinit -y -f
			mv -f -v /var/lib/aide/aide.db.new /var/lib/aide/aide.db
		fi
		touch /root/.optimizado2
	fi
}
